# Generated by Django 3.0.8 on 2020-07-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=1, upload_to='media/profile_images/'),
            preserve_default=False,
        ),
    ]
