# Generated by Django 3.0.8 on 2020-07-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/images/')),
                ('city', models.CharField(max_length=200)),
                ('contry', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('part_time', 'part_time'), ('full_time', 'full_time')], max_length=10)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
    ]
